"use client";

import { ReportSection } from "./ReportBuilder";
import SummarySection from "./sections/SummarySection";
import MetricsSection from "./sections/MetricsSection";
import ArchitectureSection from "./sections/ArchitectureSection";

export default function ReportPreview({ sections, id, data }: { sections: ReportSection[], id: string, data: Record<string, unknown> }) {
    return (
        <div className="w-full flex justify-center py-8 bg-[#222] min-h-full overflow-y-auto">
            {/* A4 Paper Container */}
            <div
                id={id}
                className="w-[210mm] min-h-[297mm] bg-white text-black shadow-2xl origin-top transition-transform duration-300"
                style={{ transform: "scale(0.85)" }} // Scale down slightly to fit Viewport
            >
                {/* Header */}
                <div className="h-32 bg-gradient-to-r from-neon-cyan via-neon-purple to-neon-pink p-8 flex items-end justify-between">
                    <div>
                        <h1 className="text-4xl font-black text-white mb-2">Architecture Report</h1>
                        <p className="text-white/80 font-mono">Generated by Architect AI</p>
                    </div>
                    <div className="text-right text-white/80">
                        <div className="font-bold">{new Date().toLocaleDateString()}</div>
                        <div className="text-sm">v1.2.0</div>
                    </div>
                </div>

                {/* Sections Rendered Here */}
                <div className="flex flex-col divide-y divide-gray-100">
                    {sections.map(section => {
                        if (!section.isVisible) return null;

                        return (
                            <div key={section.id} className="min-h-[100px]">
                                {section.id === "summary" && <SummarySection data={data} />}
                                {section.id === "architecture" && <ArchitectureSection data={data} />}
                                {section.id === "metrics" && <MetricsSection data={data} />}
                            </div>
                        );
                    })}
                </div>

                {/* Footer */}
                <div className="mt-auto p-8 border-t border-gray-200 text-center text-gray-400 text-sm">
                    Confidential Analysis • Architect AI Enterprise
                </div>
            </div>
        </div>
    );
}
